version: "3.5"

services:
        wordpress:
                image: wordpress
                ports:
                        - 80:80
                volumes:
                        - ./html:/var/www/html
                dns:
                        - 1.1.1.1
                environment:
                        WORDPRESS_DB_HOST: mysql
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD: SeattleGiveCampRocks1!
                        WORDPRESS_DB_NAME: wordpress
                depends_on:
                        - mysql

        mysql:
                image: mariadb
                ports:
                        - 3306:3306
                volumes:
                        - ./mysql/data:/var/lib/mysql
                dns:
                        - 1.1.1.1
                environment:
                        MYSQL_ROOT_PASSWORD: SeattleGiveCampRocks1!
                        MYSQL_DATABASE: wordpress

